name: 🚦 CI

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
  workflow_dispatch:

jobs:
  tests:
    name: 🧪 Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v3

      - name: Install dependencies
        run: pdm sync -d

      - name: Run Tests
        run: pdm test -svv --force-sugar --color=yes
