name: CI

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@main

      - name: Install dependencies
        run: pdm sync -d

      - name: Run Tests
        run: pdm test -v --force-sugar --color=yes
